In [1]:
import torch
import pandas as pd
# to convert from df format to tensor format, do torch.tensor(df[something].values)


In [2]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4); A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [3]:
B = A.clone() ; B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

Element-wise multimplication, or the Hadamard product, is

In [4]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

A useful operation we perform on tensors (matrices) is calculating the sum of their elements. The sum of a vector $\mathbf{x}$ of length $N$ is $\sum_{i=1}^N x_i$. In pytorcch this is just x.sum().

In [5]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

We can express sums over the elements of tensors of arbitrary shape. For example, the sum of the elements of an $m\times n$ matrix $\mathbf{A}$ could be written as $\sum_{i=1}^{m} \sum_{j=1}^{n} a_{i j}$ 

In [6]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

the sum reduces a tensor along all its axes to a scalar.

In [7]:
C = A.sum(); C

tensor(190.)

We can also sum along specific axes; to reduce the row dimension (axis 0) by summing up elements of all the rows, we specify axis=0, to sum along coumns, axis=1.

numel is the number of elements

In [8]:
A.numel()

20

In [9]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

matrix multimplication

In [10]:
B = torch.ones(4, 3)
torch.mm(A, B)
\

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])